#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/etc/netwatch/ipv6_pd_monitor.sh

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall $(basename $PROG) 2>/dev/null
}

reload_service() {
    echo "Reloading $PROG ..."
    stop_service
    sleep 1
    start_service
}

service_triggers() {
    procd_add_reload_trigger "network"
}
