#!/bin/sh

[ "$INTERFACE" = "wan" ] || exit 0

FLAG="/tmp/wan-hotplug.flag"

case "$ACTION" in
    ifup)
        logger -t ipv6-hotplug "WAN链路恢复，设置触发标志"
        touch $FLAG
        ;;
    ifdown)
        logger -t ipv6-hotplug "WAN链路断开，清除触发标志"
        rm -f $FLAG
        ;;
esac
